### ISSUE TITLE
java.lang.NoSuchMethodError: no method with name='getFontFallbackFilePath'

### ISSUE THREAD

**Issue by nomizodiac** [tangrams/tangram-es#636]
I have build tangram-es project for android using:
Ubuntu 14.04
Cmake 3.5.0
android ndk r10e
It build successfully and ask me to run demo apk using command 'adb path to apk build/demo.apk'. It runs the demo but get crashed. I cant see any logcat in terminal so i created my own demo project in Android studio and put .so files generated in tangram/libs folder while building. It throws me following exception: 

```
03-21 17:28:51.340 18017-18017/com.tpl.tplmapstangram I/dalvikvm: Could not find method android.content.res.TypedArray.getChangingConfigurations, referenced from method android.support.v7.widget.TintTypedArray.getChangingConfigurations
03-21 17:28:51.340 18017-18017/com.tpl.tplmapstangram W/dalvikvm: VFY: unable to resolve virtual method 416: Landroid/content/res/TypedArray;.getChangingConfigurations ()I
03-21 17:28:51.340 18017-18017/com.tpl.tplmapstangram I/dalvikvm: Could not find method android.content.res.TypedArray.getType, referenced from method android.support.v7.widget.TintTypedArray.getType
03-21 17:28:51.340 18017-18017/com.tpl.tplmapstangram W/dalvikvm: VFY: unable to resolve virtual method 438: Landroid/content/res/TypedArray;.getType (I)I
03-21 17:28:51.430 18017-18017/com.tpl.tplmapstangram W/dalvikvm: JNI WARNING: JNI function GetMethodID called with exception pending
03-21 17:28:51.430 18017-18017/com.tpl.tplmapstangram W/dalvikvm:              in Lcom/mapzen/tangram/MapController;.init:(Lcom/mapzen/tangram/MapController;Landroid/content/res/AssetManager;Ljava/lang/String;)V (GetMethodID)
03-21 17:28:51.430 18017-18017/com.tpl.tplmapstangram W/dalvikvm: Pending exception is:
03-21 17:28:51.430 18017-18017/com.tpl.tplmapstangram I/dalvikvm: java.lang.NoSuchMethodError: no method with name='getFontFallbackFilePath' signature='(II)Ljava/lang/String;' in class Lcom/mapzen/tangram/MapController;
03-21 17:28:51.430 18017-18017/com.tpl.tplmapstangram I/dalvikvm:     at com.mapzen.tangram.MapController.init(Native Method)
03-21 17:28:51.430 18017-18017/com.tpl.tplmapstangram I/dalvikvm:     at com.mapzen.tangram.MapController.<init>(MapController.java:94)
03-21 17:28:51.430 18017-18017/com.tpl.tplmapstangram I/dalvikvm:     at com.mapzen.tangram.MapController.<init>(MapController.java:55)
```

```
03-21 17:28:51.430 18017-18017/com.tpl.tplmapstangram I/dalvikvm: "main" prio=5 tid=1 NATIVE
03-21 17:28:51.430 18017-18017/com.tpl.tplmapstangram I/dalvikvm:   | group="main" sCount=0 dsCount=0 obj=0x4163dd80 self=0x41574720
03-21 17:28:51.430 18017-18017/com.tpl.tplmapstangram I/dalvikvm:   | sysTid=18017 nice=-1 sched=0/0 cgrp=apps handle=1074446676
03-21 17:28:51.430 18017-18017/com.tpl.tplmapstangram I/dalvikvm:   | state=R schedstat=( 176471883 24224473 67 ) utm=13 stm=4 core=2
03-21 17:28:51.440 18017-18017/com.tpl.tplmapstangram I/dalvikvm:   #00  pc 000012f6  /system/lib/libcorkscrew.so (unwind_backtrace_thread+29)
03-21 17:28:51.440 18017-18017/com.tpl.tplmapstangram I/dalvikvm:   #01  pc 00061890  /system/lib/libdvm.so (dvmDumpNativeStack(DebugOutputTarget const*, int)+31)
03-21 17:28:51.440 18017-18017/com.tpl.tplmapstangram I/dalvikvm:   #02  pc 00055880  /system/lib/libdvm.so (dvmDumpThreadEx(DebugOutputTarget const*, Thread*, bool)+395)
03-21 17:28:51.440 18017-18017/com.tpl.tplmapstangram I/dalvikvm:   #03  pc 000558ee  /system/lib/libdvm.so (dvmDumpThread(Thread*, bool)+25)
03-21 17:28:51.440 18017-18017/com.tpl.tplmapstangram I/dalvikvm:   #04  pc 00039a3c  /system/lib/libdvm.so
03-21 17:28:51.440 18017-18017/com.tpl.tplmapstangram I/dalvikvm:   #05  pc 00041eb8  /system/lib/libdvm.so
03-21 17:28:51.440 18017-18017/com.tpl.tplmapstangram I/dalvikvm:   #06  pc 00086cdc  /data/app-lib/com.tpl.tplmapstangram-2/libtangram.so (setupJniEnv(_JNIEnv*, _jobject*, _jobject*)+175)
03-21 17:28:51.440 18017-18017/com.tpl.tplmapstangram I/dalvikvm:   #07  pc 000840a4  /data/app-lib/com.tpl.tplmapstangram-2/libtangram.so (Java_com_mapzen_tangram_MapController_init+7)
03-21 17:28:51.440 18017-18017/com.tpl.tplmapstangram I/dalvikvm:   #08  pc 0001eb0c  /system/lib/libdvm.so (dvmPlatformInvoke+112)
03-21 17:28:51.440 18017-18017/com.tpl.tplmapstangram I/dalvikvm:   #09  pc 0004f372  /system/lib/libdvm.so (dvmCallJNIMethod(unsigned int const*, JValue*, Method const*, Thread*)+397)
03-21 17:28:51.440 18017-18017/com.tpl.tplmapstangram I/dalvikvm:   #10  pc 00050d42  /system/lib/libdvm.so (dvmResolveNativeMethod(unsigned int const*, JValue*, Method const*, Thread*)+181)
03-21 17:28:51.440 18017-18017/com.tpl.tplmapstangram I/dalvikvm:   #11  pc 00027f20  /system/lib/libdvm.so
03-21 17:28:51.440 18017-18017/com.tpl.tplmapstangram I/dalvikvm:   #12  pc 0002f24c  /system/lib/libdvm.so (dvmMterpStd(Thread*)+76)
03-21 17:28:51.440 18017-18017/com.tpl.tplmapstangram I/dalvikvm:   #13  pc 0002c8f8  /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+184)
03-21 17:28:51.440 18017-18017/com.tpl.tplmapstangram I/dalvikvm:   #14  pc 00061aa4  /system/lib/libdvm.so (dvmInvokeMethod(Object*, Method const*, ArrayObject*, ArrayObject*, ClassObject*, bool)+391)
03-21 17:28:51.440 18017-18017/com.tpl.tplmapstangram I/dalvikvm:   #15  pc 00069bae  /system/lib/libdvm.so
03-21 17:28:51.440 18017-18017/com.tpl.tplmapstangram I/dalvikvm:   #16  pc 00027f20  /system/lib/libdvm.so
03-21 17:28:51.440 18017-18017/com.tpl.tplmapstangram I/dalvikvm:   #17  pc 0002f24c  /system/lib/libdvm.so (dvmMterpStd(Thread*)+76)
03-21 17:28:51.440 18017-18017/com.tpl.tplmapstangram I/dalvikvm:   #18  pc 0002c8f8  /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+184)
03-21 17:28:51.440 18017-18017/com.tpl.tplmapstangram I/dalvikvm:   #19  pc 000617c2  /system/lib/libdvm.so (dvmCallMethodV(Thread*, Method const*, Object*, bool, JValue*, std::__va_list)+337)
03-21 17:28:51.440 18017-18017/com.tpl.tplmapstangram I/dalvikvm:   #20  pc 0004af3a  /system/lib/libdvm.so
03-21 17:28:51.440 18017-18017/com.tpl.tplmapstangram I/dalvikvm:   #21  pc 0004f2a0  /system/lib/libandroid_runtime.so
03-21 17:28:51.440 18017-18017/com.tpl.tplmapstangram I/dalvikvm:   #22  pc 00050054  /system/lib/libandroid_runtime.so (android::AndroidRuntime::start(char const*, char const*)+367)
03-21 17:28:51.440 18017-18017/com.tpl.tplmapstangram I/dalvikvm:   #23  pc 0000105a  /system/bin/app_process
03-21 17:28:51.440 18017-18017/com.tpl.tplmapstangram I/dalvikvm:   #24  pc 0000e5e8  /system/lib/libc.so (__libc_init+47)
03-21 17:28:51.440 18017-18017/com.tpl.tplmapstangram I/dalvikvm:     at com.mapzen.tangram.MapController.init(Native Method)
03-21 17:28:51.440 18017-18017/com.tpl.tplmapstangram I/dalvikvm:     at com.mapzen.tangram.MapController.<init>(MapController.java:94)
03-21 17:28:51.440 18017-18017/com.tpl.tplmapstangram I/dalvikvm:     at com.mapzen.tangram.MapController.<init>(MapController.java:55)
```

```
03-21 17:28:51.440 18017-18017/com.tpl.tplmapstangram E/dalvikvm: VM aborting
03-21 17:28:51.440 18017-18017/com.tpl.tplmapstangram A/libc: Fatal signal 6 (SIGABRT) at 0x00004661 (code=-6), thread 18017 (.tplmapstangram)
```
I have also got pre generated .so files from another [tangram project](https://github.com/tangrams/tangram-cardboard) and they are working fine. Have i done something wrong while building if yes then why it bulids successfully without any errors?

**Comment by tallytalwar** [comment]
Hey Nouman

Thanks for logs.

Although I can not reproduce the crash, I think this might be happening because your project is not updated with the changes in tangram-es. This specific `getFontFallbackFilePath` is a very recent change (was pushed to master last Friday). Are you sure you have your branch up-to date? I would do a `git pull` to make sure you are running of the latest source code.

Regarding why such JNI errors are not caught during build process, is because JNI function signature check can not take place while the application is being build, it can only correlate to the signatures in the .class file once it has been build.

Let us know, if updating the project with the latest code from tangram-es master does not resolve this for you?

Thanks

**Comment by nomizodiac** [comment]
Hi @tallytalwar Thanks for response.

I am not using git to clone the project. I had manually downloaded the project and then also added submodules manually in 'external' folder. But now i did whole process again following steps:

step1: `git clone --recursive git://github.com/tangrams/tangram-es.git`
step2: `git submodule update --init --recursive`

It clones all modules and submodules successfully 

step3: `make android`

It builds the project for armeabi-v7 successfully 
Then i run demo `'adb path to apk build/demo.apk' ` It deploys app on device and again get crashed. But the strange thing that i noticed is that when i run same build and apk on my other device which is Nexus-5 Marshmallow 6.0 it works. But didnt work on any other device i have tested on Huawei Honor 4C CHM-U01 4.4 and Samsung Galaxy s3 4.4.

One other thing to notice is that now when i use the generated .so files in the separate demo app that i have created in android studio. It doesn't throw me java.lang.NoSuchMethodError: no method with name='getFontFallbackFilePath' exception. It simply get crashed on Honor 4C CHM-U01 4.4 without any exceptions in logcat. And In this scenerio it did even work on Nexus-5 Marshmallow 6.0 correctly it didnt get crashed on nexus but shows complete blue screen and following logcat:

```
03-22 17:07:29.823 32540-32540/com.tpl.tplmapstangram I/art: Late-enabling -Xcheck:jni
03-22 17:07:30.000 32540-32540/com.tpl.tplmapstangram D/Tangram: TANGRAM tangram.cpp:73: initialize
03-22 17:07:30.000 32540-32540/com.tpl.tplmapstangram D/Tangram: TANGRAM tangram.cpp:104: Loading scene file: scene.yaml
03-22 17:07:30.067 32540-32540/com.tpl.tplmapstangram D/Tangram: TANGRAM fontContext.cpp:34: FONT /system/fonts/Roboto-Regular.ttf
03-22 17:07:30.067 32540-32540/com.tpl.tplmapstangram D/Tangram: TANGRAM fontContext.cpp:53: FALLBACK /system/fonts/NotoNaskhArabic-Regular.ttf
03-22 17:07:30.069 32540-32540/com.tpl.tplmapstangram D/Tangram: TANGRAM fontContext.cpp:53: FALLBACK /system/fonts/NotoSansNKo-Regular.ttf
03-22 17:07:30.069 32540-32540/com.tpl.tplmapstangram D/Tangram: TANGRAM fontContext.cpp:53: FALLBACK /system/fonts/NotoSansOlChiki-Regular.ttf
03-22 17:07:30.069 32540-32540/com.tpl.tplmapstangram D/Tangram: TANGRAM fontContext.cpp:53: FALLBACK /system/fonts/NotoSansRejang-Regular.ttf
03-22 17:07:30.069 32540-32540/com.tpl.tplmapstangram D/Tangram: TANGRAM fontContext.cpp:53: FALLBACK /system/fonts/NotoSansSaurashtra-Regular.ttf
03-22 17:07:30.070 32540-32540/com.tpl.tplmapstangram D/Tangram: TANGRAM fontContext.cpp:53: FALLBACK /system/fonts/NotoSansSundanese-Regular.ttf
03-22 17:07:30.070 32540-32540/com.tpl.tplmapstangram D/Tangram: TANGRAM fontContext.cpp:53: FALLBACK /system/fonts/NotoSansSylotiNagri-Regular.ttf
03-22 17:07:30.070 32540-32540/com.tpl.tplmapstangram D/Tangram: TANGRAM fontContext.cpp:53: FALLBACK /system/fonts/NotoSansSyriacEstrangela-Regular.ttf
03-22 17:07:30.110 32540-32540/com.tpl.tplmapstangram D/Tangram: TANGRAM tileManager.cpp:67: add source osm
03-22 17:07:30.115 32540-32540/com.tpl.tplmapstangram D/Tangram: TANGRAM tangram.cpp:99: finish initialize
03-22 17:07:30.141 32540-32602/com.tpl.tplmapstangram D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
03-22 17:07:30.236 32540-32602/com.tpl.tplmapstangram I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, 369a2ea, I96aee987eb
03-22 17:07:30.243 32540-32602/com.tpl.tplmapstangram I/OpenGLRenderer: Initialized EGL, version 1.4
03-22 17:07:30.297 32540-32587/com.tpl.tplmapstangram D/Tangram: TANGRAM tangram.cpp:69: Notice: Already initialized
03-22 17:07:30.297 32540-32587/com.tpl.tplmapstangram D/Tangram: TANGRAM tangram.cpp:577: setup GL
03-22 17:07:30.307 32540-32587/com.tpl.tplmapstangram D/Tangram: TANGRAM hardware.cpp:56: Driver supports map buffer: 0
03-22 17:07:30.307 32540-32587/com.tpl.tplmapstangram D/Tangram: TANGRAM hardware.cpp:57: Driver supports vaos: 1
03-22 17:07:30.308 32540-32587/com.tpl.tplmapstangram D/Tangram: TANGRAM hardware.cpp:71: Hardware max texture size 4096
03-22 17:07:30.308 32540-32587/com.tpl.tplmapstangram D/Tangram: TANGRAM hardware.cpp:72: Hardware max combined texture units 32
03-22 17:07:30.309 32540-32587/com.tpl.tplmapstangram D/Tangram: TANGRAM tangram.cpp:132: resize: 1080 x 1704
03-22 17:07:30.318 32540-32589/com.tpl.tplmapstangram D/Tangram: TANGRAM tileWorker.cpp:70: Passed new TileBuilder to TileWorker
03-22 17:07:30.318 32540-32588/com.tpl.tplmapstangram D/Tangram: TANGRAM tileWorker.cpp:70: Passed new TileBuilder to TileWorker
03-22 17:07:30.496 32540-32589/com.tpl.tplmapstangram D/Tangram: Failed to open asset at path: fonts/sans-serif-400normal.ttf
03-22 17:07:30.496 32540-32589/com.tpl.tplmapstangram D/Tangram: Failed to open asset at path: fonts/sans-serif-400normal.ttf
03-22 17:07:30.515 32540-32589/com.tpl.tplmapstangram I/Alfons: LOADED Font: Roboto Regular size: 52

```
This is strange that it builds and run demo app on Nexus-5 from terminal build (cmake make android) but does not work on same device using (generated .so files) plus it didnt work on any other device with any method (cmake build or generated .so files).

**Comment by tallytalwar** [comment]
Hi @nomizodiac

As you mentioned by default our build instructions will build for `armeabi-v7` architecture. It looks like your Huawei device is arm64, can you verify it by building the right architecture for each device and trying the process again. And since it consistently works on Nexus5 (armv7 arch), shows that it could be an architecture issue where you are not building the tangram library for the right architecture.

With respect to deploying `.so` in another app, can you elaborate on the sequence of steps you are doing? Also we have a **Early BETA** package living on maven central [here](http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22tangram%22) which you can use directly instead of bundling a `.so` manually with your own demo app.

**Comment by nomizodiac** [comment]
Hi @tallytalwar 

Yes i also thought that it may be the issue of different architecture so thats why i had already tried to generate build for all architectures still it wont work on other devices except Nexus5. I also tested on Samsung galaxy s3 and i think it also has same (armv7 arch) as Nexus. Can you please verify if following is the right way to generate builds for all architectures

`make android [ANDROID_ARCH=x86 armeabi-v7a armeabi]
`

Because i wasn't able to generate build for all arch the way that is mentioned for Android which is:

`make android [ANDROID_ARCH=[x86|armeabi-v7a|armeabi]]
`

May be i am missing something here.

To deploy .so files basically i am using the same demo app which is in tangram-es project. But instead of cpp files in jni folder i have created jniLibs folder and adding .so files in it and deleted jni folder. And this demo app works fine (for all devices) when i deploy .so files that i have got from your [other project](https://github.com/tangrams/tangram-cardboard) but wont work if i put my own generated .so files in jniLibs folder.

**Comment by blair1618** [comment]
@nomizodiac Are you still having this same issue?

Copy-pasting compiled libraries is probably going to cause breakage because the Java-C++ interface in tangram-es changes frequently. If you're following the build process in the README we can help with that, *or* you can now pull in tangram-es as a library dependency to any Android project (it's on maven central [here](http://search.maven.org/#search|ga|1|a%3A%22tangram%22)). The current library release does not have the latest features and fixes, but it means you don't have to build the library yourself.

**Comment by blair1618** [comment]
JNI issues like this should no longer be an issue as the library can now be obtained, fully compiled and linked, from maven central.
